name: ci

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          run: git fetch --prune --unshallow
      - uses: actions/setup-go@v2
      - run: go vet ./...
      - run: go test ./...

      # Only store binaries to Github Releases on tag.
      - uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist --config .github/goreleaser.yml

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
